[prune]
  go-tests = true

[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "v2.2.6"

[[constraint]]
  name = "github.com/go-yaml/yaml"
  version = "v2.2.1"

[[constraint]]
  name = "github.com/jacobsa/go-serial"
  branch = "master"
